{% set name = "xscen" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xscen-{{ version }}.tar.gz
  sha256: 08f5545b3082ba9b8ca22bb9c4bda125cb41505391b94f47d9fb6600a2d2ca2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - babel
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >=3.9
    # Main package
    - babel
    - cartopy
    - cftime
    - cf_xarray >=0.7.6
    - clisops >=0.10.0
    - dask-core
    - flox
    - fsspec <2023.10.0
    - geopandas
    - h5netcdf
    - h5py
    - intake-esm >=2023.07.07,<2024.2.6  # v2024.2.6 drops Python3.9 support
    - matplotlib-base
    - netCDF4
    - numcodecs
    - numpy
    - pandas >=2.0
    - parse
    - pyyaml
    - rechunker
    - scipy
    - shapely >=2.0
    - sparse <=0.14  # 0.15 breaks xe.SpatialAverager (https://github.com/Ouranosinc/xscen/actions/runs/7463533566/job/20308477398)
    - toolz
    - xarray <2023.11.0  # FIXME: Remove when pandas 2.2 is released and xclim is fixed.
    - xclim >=0.46
    - xesmf >=0.7
    - zarr
    # Opt
    - nc-time-axis >=1.3.1
    - pyarrow >=1.0.0  # Used when opening catalogs

test:
  imports:
    - xscen
  # source_files:
  #   - tests
  commands:
    - pip check
  #   - pytest tests
  requires:
    - pip
  #   - pytest
  #   - xdoctest

about:
  home: https://github.com/Ouranosinc/xscen
  summary: A climate change scenario-building analysis framework, built with xclim/xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aulemahal
    - juliettelavoie
    - RondeauG
    - Zeitsperre
